# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/run_combfold_assembly.smk"
include: "rules/prepare_subunits_json.smk"
include: "rules/multiqc.smk"

# local rules
localrules: PREPARE_SUBUNITS_JSON
    
# -----------------------------------------------------


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        "results/rule_MULTIQC/multiqc_report.html",
