fasta: "/scratch1/home/nnagar/repos/CombFold/example/example.fasta"
output_dir: "results"
pdb_dir: "/scratch1/home/nnagar/repos/CombFold/example/pdbs"
combfold_container: "docker://ntnn19/combfold"
stoichiometry: "NS1:1-6,NS2A:1-4"